// This file is generated by Astro DB
declare module 'astro:db' {
	export const Views: import("@astrojs/db/runtime").Table<
		"Views",
		{"slug":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"slug","collection":"Views","primaryKey":true}},"count":{"type":"number","schema":{"unique":false,"deprecated":false,"name":"count","collection":"Views","primaryKey":false,"optional":false,"default":1}}}
	>;
}
